### ISSUE TITLE
[GUI] Re-pensar el informar

### ISSUE THREAD

**Issue by gonetil** [J-Josu/RobotScript#3]
Para la sentencia "Informar" se puede mostrar un mensaje similar a R-Info mediante la función alert de javascript. Sin embargo, quizás sea conveniente implementar una consola con la salida del programa (similar a lo que se haría con un console.log, pero visible para el usuario). De este modo, se pueden informar varios mensajes, no será necesario hacer clic en aceptar en cada uno de ellos, y además el usuario tendrá el historial de mensajes informados en dicha consola.
Cada mensaje debería incluir:
- robot (variable y tipo) que emitió el mensaje
- alguna marca de tiempo (timestamp, datetime, etc.)
- un número de secuencia (el primer mensaje será el 1, el siguiente será el 2, etc...)

**Comment by J-Josu** [comment]
Momentáneamente añadí la función para el informar, pero tengo que diseñar bien la consola o barra de estado para que ande todo perfecto
Probe con este código y funciono :
  programa prueba
  areas
    ciudad : AreaC(1,1,100,100)
  robots
    robot rinfo
    variables
      aux : numero
    comenzar
      aux := 100
      repetir (aux / 2) comenzar
    	  Informar(aux)
    	  aux := aux -2
  	  fin
    fin
  variables 
    r1 : rinfo
  comenzar
    AsignarArea(r1,ciudad)
    Iniciar(r1,1,1)
  fin
