### ISSUE TITLE
[COMPILADOR] [GUI] Controlar los límites de la ciudad y del área asignada al robot

### ISSUE THREAD

**Issue by gonetil** [J-Josu/RobotScript#5]
Cuando un robot se sale de su área (ver ejemplo abajo) o incluso cuando se pasa de los límites de la ciudad, no se genera ningún error ni se advierte al usuario.
Aquí hay dos tipos de errores:
- desde el punto de vista del compilador, debe verificarse la posición del robot, para confirmar que al moverse se encuentre dentro de un área asignada y que también esté en la ciudad
- desde el punto de vista de la GUI, se debe advertir al usuario mediante algún mensaje de error claro (se salió del área, se salió de la ciudad) y abortar la ejecución del programa

```
programa prueba
areas
  ciudad : AreaC(1,1,10,10)
robots
  robot rinfo
  variables
    aux : numero
  comenzar
    aux := 100
    repetir (12)
      mover
    Informar(aux)
  fin
variables 
  r1 : rinfo
comenzar
  AsignarArea(r1,ciudad)
  Iniciar(r1,1,1)
fin
```

**Comment by J-Josu** [comment]
Teoricamente ya se hacen las comprobaciones con mensaje de error pertinentes
